---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume-tomcat
  namespace: tomcat
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
