---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-tomcat
  namespace: tomcat
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
