---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: tomcat
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-container
        image: tomcat:8.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "250Mi"
            cpu: "500m"
        volumeMounts:
        - name: tomcat-persistent-storage
          mountPath: /var/lib/tomcat
      volumes:
      - name: tomcat-persistent-storage
        persistentVolumeClaim:
          claimName: pv-volume-tomcat
